version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\MSBuild.exe" "C:\projects\protein-digestion-simulator\ProteinDigestionSimulator.NET.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'
artifacts:
- path: bin
  name: Protein-Digestion-Simulator