version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: ProteinDigestionSimulator.NET.sln
  verbosity: minimal
artifacts:
- path: bin
  name: Protein-Digestion-Simulator